### ISSUE TITLE
Using.ejs template: getting "Module build failed: TypeError: Path must be a string."

### ISSUE THREAD

**Issue by warpdesign** [GoogleChromeLabs/prerender-loader#5] opened 2018-05-31 15:16 UTC
I am using an .ejs template, like this:

```js
        new HtmlWebpackPlugin({
            template: 'src/html/index.ejs',
            title: package_json.name
        })
```

I followed the instructions and changed it to:

```js
        new HtmlWebpackPlugin({
            template: '!!prerender-loader?string!./src/html/index.ejs',
            title: package_json.name
        })
```

But this gives this erorr:

> ERROR in   Error: Child compilation failed:
  Module build failed: TypeError: Path must be a string. Received [ 'E:\\Docs\\Dev\\react-500px\\node_modules\\webpack-dev-server\\client\\index.js?http://127.0.0.1:8888',

Is there something special to do when using .ejs (or other format) templates?

My full webpack.config.js can be seen [here](https://github.com/warpdesign/react-500px/blob/master/webpack.config.js).

**Comment by rkichenama** [comment] 2018-05-31 15:28
Please see #3

**Comment by warpdesign** [comment] 2018-05-31 15:52
Hmm... so the problem has nothing to do with the .esj, but more with my webpack configuration.

The `entry` property is an array:

```
    entry: [
        'webpack-dev-server/client?http://127.0.0.1:8888',
        'webpack/hot/only-dev-server',
        /* default to index.js file since there's no filename here */
        'es6-promise',
        'whatwg-fetch',
        './src'
    ],
```

That's what's in parentCompiler.options.entry where the crash happens.

**Comment by developit** [comment] 2018-05-31 20:38
Yup - looks like we need to take multi-entry configuration into account on this line:
https://github.com/GoogleChromeLabs/prerender-loader/blob/5f667781679351b8f160a0e39e0deb45099d2848/src/index.js#L128

I'll close this out since it's a duplicate of #3.

**Closed by developit** 2018-05-31 20:38 UTC
